### ISSUE TITLE
A couple references

### ISSUE THREAD

**Issue by nh2** [the8472/platter-walk#1]
Hi, I just found your project.

Just wanted to make you aware of some writeup I had done when I investigated disk-order traversals, in particular for the references the README contains:

https://github.com/nh2/diskorder

I asked for the authors of the `qtar` paper whether they could release the code, and they did: https://github.com/chlunde/qtar

Maybe this can be helpful for benchmarks / comparisons / implementation details.

I also added a link to your project at https://github.com/nh2/diskorder#similar-work -- IMO these kinds of techniques should be much more well-known.

**Comment by the8472** [comment]
Your readme says

> Performance can be optionally be improved further by combining this approach with readahead().

You might be interested in https://github.com/the8472/reapfrog which can be combined with platter-walk to achieve both.

**Comment by nh2** [comment]
Cool, thanks!
